### ISSUE TITLE
export more than 65K rows to excel

### ISSUE THREAD

**Issue by GAHila** [nwwells/grails-export#8]
Is it possible to export more than 65k rows to excel with this plugin?  I have Excel 2013 and it allows up to a million rows to be exported (given no memory issues). However, when I export more than 65k of rows I get: Message: The maximum number of rows permitted on a worksheet been exceeded.

I even changed the MIME type to match the default one for xlsx but that did not make a difference.

Thank you very much,

**Comment by nwwells** [comment]
This project has been moved to the Grail Plugin Collective. You can access it here:

https://github.com/gpc/grails-export
